# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_header_using_SeqLib <- function(file_name) {
    .Call('_STITCH_get_header_using_SeqLib', PACKAGE = 'STITCH', file_name)
}

#' @export
get_read_span <- function(cigarLengthVec, cigarTypeVec) {
    .Call('_STITCH_get_read_span', PACKAGE = 'STITCH', cigarLengthVec, cigarTypeVec)
}

#' @export
cpp_cigar_split_many <- function(strings) {
    .Call('_STITCH_cpp_cigar_split_many', PACKAGE = 'STITCH', strings)
}

#' @export
cpp_deal_with_soft_clipped_bases <- function(splitCigarRead, useSoftClippedBases, posRead, seqRead, qualRead) {
    .Call('_STITCH_cpp_deal_with_soft_clipped_bases', PACKAGE = 'STITCH', splitCigarRead, useSoftClippedBases, posRead, seqRead, qualRead)
}

#' @export
get_sample_data_from_SeqLib <- function(region, file_name, reference = "") {
    .Call('_STITCH_get_sample_data_from_SeqLib', PACKAGE = 'STITCH', region, file_name, reference)
}

#' @export
get_sampleReadsRaw_from_SeqLib <- function(useSoftClippedBases, bqFilter, iSizeUpperLimit, ref, alt, nSNPs, L, region, file_name, reference = "", save_sampleReadsInfo = FALSE) {
    .Call('_STITCH_get_sampleReadsRaw_from_SeqLib', PACKAGE = 'STITCH', useSoftClippedBases, bqFilter, iSizeUpperLimit, ref, alt, nSNPs, L, region, file_name, reference, save_sampleReadsInfo)
}

#' @export
collapse_diploid_gamma <- function(gamma_t, gammaK_t, prev, suppressOutput, prev_section, next_section) {
    invisible(.Call('_STITCH_collapse_diploid_gamma', PACKAGE = 'STITCH', gamma_t, gammaK_t, prev, suppressOutput, prev_section, next_section))
}

#' @export
rcpp_make_and_bound_eMatGrid_diploid_t <- function(eMatGrid_t, eMatRead_t, sampleReads, maxEmissionMatrixDifference, prev, suppressOutput, prev_section, next_section, run_fb_grid_offset = 0L, rescale_eMatGrid_t = TRUE) {
    invisible(.Call('_STITCH_rcpp_make_and_bound_eMatGrid_diploid_t', PACKAGE = 'STITCH', eMatGrid_t, eMatRead_t, sampleReads, maxEmissionMatrixDifference, prev, suppressOutput, prev_section, next_section, run_fb_grid_offset, rescale_eMatGrid_t))
}

#' @export
sample_diploid_path <- function(alphaHat_t, transMatRate_t_D, eMatGrid_t, alphaMat_t, T, K, c) {
    .Call('_STITCH_sample_diploid_path', PACKAGE = 'STITCH', alphaHat_t, transMatRate_t_D, eMatGrid_t, alphaMat_t, T, K, c)
}

#' @export
rcpp_make_diploid_jUpdate <- function(alphaMatSum_tc, s, alphaHat_t, betaHat_t, transMatRate_tc_D, alphaMatCurrent_tc, eMatGrid_t, prev, suppressOutput, prev_section, next_section) {
    invisible(.Call('_STITCH_rcpp_make_diploid_jUpdate', PACKAGE = 'STITCH', alphaMatSum_tc, s, alphaHat_t, betaHat_t, transMatRate_tc_D, alphaMatCurrent_tc, eMatGrid_t, prev, suppressOutput, prev_section, next_section))
}

#' @export
rcpp_calculate_fbd_dosage <- function(genProbs_t, eHapsCurrent_tc, s, gamma_t, grid, snp_start_1_based, snp_end_1_based, prev, suppressOutput, prev_section, next_section, grid_offset = 0L) {
    invisible(.Call('_STITCH_rcpp_calculate_fbd_dosage', PACKAGE = 'STITCH', genProbs_t, eHapsCurrent_tc, s, gamma_t, grid, snp_start_1_based, snp_end_1_based, prev, suppressOutput, prev_section, next_section, grid_offset))
}

#' @export
forwardBackwardDiploid <- function(sampleReads, eHapsCurrent_tc, alphaMatCurrent_tc, transMatRate_tc_D, priorCurrent_m, alphaHat_t, betaHat_t, gamma_t, eMatGrid_t, maxDifferenceBetweenReads, maxEmissionMatrixDifference, Jmax, suppressOutput, blocks_for_output, gammaSum0_tc, gammaSum1_tc, alphaMatSum_tc, hapSum_tc, priorSum_m, prev_list_of_alphaBetaBlocks, i_snp_block_for_alpha_beta = 0L, generate_fb_snp_offsets = FALSE, return_a_sampled_path = FALSE, run_fb_subset = FALSE, run_fb_grid_offset = 0L, return_genProbs = FALSE, snp_start_1_based = -1L, snp_end_1_based = -1L, grid = 0L, return_gamma = FALSE, return_extra = FALSE, update_in_place = FALSE, pass_in_alphaBeta = FALSE, output_haplotype_dosages = FALSE, rescale_eMatGrid_t = TRUE) {
    .Call('_STITCH_forwardBackwardDiploid', PACKAGE = 'STITCH', sampleReads, eHapsCurrent_tc, alphaMatCurrent_tc, transMatRate_tc_D, priorCurrent_m, alphaHat_t, betaHat_t, gamma_t, eMatGrid_t, maxDifferenceBetweenReads, maxEmissionMatrixDifference, Jmax, suppressOutput, blocks_for_output, gammaSum0_tc, gammaSum1_tc, alphaMatSum_tc, hapSum_tc, priorSum_m, prev_list_of_alphaBetaBlocks, i_snp_block_for_alpha_beta, generate_fb_snp_offsets, return_a_sampled_path, run_fb_subset, run_fb_grid_offset, return_genProbs, snp_start_1_based, snp_end_1_based, grid, return_gamma, return_extra, update_in_place, pass_in_alphaBeta, output_haplotype_dosages, rescale_eMatGrid_t)
}

#' @export
rcpp_make_sampleReads_from_hap <- function(non_NA_cols, reference_phred, reference_hap) {
    .Call('_STITCH_rcpp_make_sampleReads_from_hap', PACKAGE = 'STITCH', non_NA_cols, reference_phred, reference_hap)
}

#' @export
increment2N <- function(yT, xT, y, z) {
    .Call('_STITCH_increment2N', PACKAGE = 'STITCH', yT, xT, y, z)
}

#' @export
ram_test <- function(mat1, mat2, mat3, mat4) {
    .Call('_STITCH_ram_test', PACKAGE = 'STITCH', mat1, mat2, mat3, mat4)
}

#' @export
get_min_from_position <- function(match_vec, readStart_all, readEnd_all, readMin, readMax) {
    invisible(.Call('_STITCH_get_min_from_position', PACKAGE = 'STITCH', match_vec, readStart_all, readEnd_all, readMin, readMax))
}

#' @export
get_random_values <- function(N) {
    .Call('_STITCH_get_random_values', PACKAGE = 'STITCH', N)
}

#' @export
rcpp_make_fb_snp_offsets <- function(alphaHat_t, betaHat_t, blocks_for_output) {
    .Call('_STITCH_rcpp_make_fb_snp_offsets', PACKAGE = 'STITCH', alphaHat_t, betaHat_t, blocks_for_output)
}

#' @export
cpp_read_reassign <- function(ord, qnameInteger_ord, qname, strand, sampleReadsRaw, readStart_ord, readEnd_ord, readStart, readEnd, iSizeUpperLimit, save_sampleReadsInfo = FALSE) {
    .Call('_STITCH_cpp_read_reassign', PACKAGE = 'STITCH', ord, qnameInteger_ord, qname, strand, sampleReadsRaw, readStart_ord, readEnd_ord, readStart, readEnd, iSizeUpperLimit, save_sampleReadsInfo)
}

#' @export
make_gammaEK_t_from_gammaK_t <- function(gammaK_t, K, grid, snp_start_1_based, snp_end_1_based, prev, suppressOutput, prev_section, next_section, grid_offset = 0L) {
    .Call('_STITCH_make_gammaEK_t_from_gammaK_t', PACKAGE = 'STITCH', gammaK_t, K, grid, snp_start_1_based, snp_end_1_based, prev, suppressOutput, prev_section, next_section, grid_offset)
}

#' @export
Rcpp_run_forward_haploid <- function(alphaHat_t, c, eMatGrid_t, alphaMatCurrent_tc, transMatRate_tc_H, priorCurrent_m, s, alphaStart = 0L, run_fb_subset = FALSE) {
    invisible(.Call('_STITCH_Rcpp_run_forward_haploid', PACKAGE = 'STITCH', alphaHat_t, c, eMatGrid_t, alphaMatCurrent_tc, transMatRate_tc_H, priorCurrent_m, s, alphaStart, run_fb_subset))
}

#' @export
Rcpp_run_backward_haploid <- function(betaHat_t, c, eMatGrid_t, alphaMatCurrent_tc, transMatRate_tc_H, s) {
    invisible(.Call('_STITCH_Rcpp_run_backward_haploid', PACKAGE = 'STITCH', betaHat_t, c, eMatGrid_t, alphaMatCurrent_tc, transMatRate_tc_H, s))
}

#' @export
rcpp_make_eMatRead_t <- function(eMatRead_t, sampleReads, eHapsCurrent_tc, s, maxDifferenceBetweenReads, Jmax, eMatHapOri_t, pRgivenH1, pRgivenH2, prev, suppressOutput, prev_section, next_section, run_pseudo_haploid = FALSE, rescale_eMatRead_t = TRUE) {
    invisible(.Call('_STITCH_rcpp_make_eMatRead_t', PACKAGE = 'STITCH', eMatRead_t, sampleReads, eHapsCurrent_tc, s, maxDifferenceBetweenReads, Jmax, eMatHapOri_t, pRgivenH1, pRgivenH2, prev, suppressOutput, prev_section, next_section, run_pseudo_haploid, rescale_eMatRead_t))
}

#' @export
rcpp_make_eMatGrid_t <- function(eMatGrid_t, eMatRead_t, H, sampleReads, hap, nGrids, prev, suppressOutput, prev_section, next_section, run_fb_grid_offset = 0L, use_all_reads = FALSE, bound = FALSE, maxEmissionMatrixDifference = 1000, rescale = FALSE) {
    invisible(.Call('_STITCH_rcpp_make_eMatGrid_t', PACKAGE = 'STITCH', eMatGrid_t, eMatRead_t, H, sampleReads, hap, nGrids, prev, suppressOutput, prev_section, next_section, run_fb_grid_offset, use_all_reads, bound, maxEmissionMatrixDifference, rescale))
}

#' @export
make_haploid_gammaUpdate_t <- function(s, gammaSum0_tc, gammaSum1_tc, sampleReads, gamma_t, eHapsCurrent_tc, eMatRead_t, eMatHapOri_t, pRgivenH1, pRgivenH2, run_pseudo_haploid = FALSE) {
    invisible(.Call('_STITCH_make_haploid_gammaUpdate_t', PACKAGE = 'STITCH', s, gammaSum0_tc, gammaSum1_tc, sampleReads, gamma_t, eHapsCurrent_tc, eMatRead_t, eMatHapOri_t, pRgivenH1, pRgivenH2, run_pseudo_haploid))
}

#' @export
pseudoHaploid_update_model_9 <- function(pRgivenH1, pRgivenH2, eMatRead_t1, eMatRead_t2, gamma_t1, gamma_t2, K, srp) {
    .Call('_STITCH_pseudoHaploid_update_model_9', PACKAGE = 'STITCH', pRgivenH1, pRgivenH2, eMatRead_t1, eMatRead_t2, gamma_t1, gamma_t2, K, srp)
}

#' @export
forwardBackwardHaploid <- function(sampleReads, eHapsCurrent_tc, alphaMatCurrent_tc, transMatRate_tc_H, priorCurrent_m, alphaHat_t, betaHat_t, gamma_t, eMatGrid_t, maxDifferenceBetweenReads, maxEmissionMatrixDifference, Jmax, suppressOutput, model, gammaSum0_tc, gammaSum1_tc, alphaMatSum_tc, hapSum_tc, priorSum_m, pRgivenH1, pRgivenH2, run_pseudo_haploid, blocks_for_output, prev_list_of_alphaBetaBlocks, i_snp_block_for_alpha_beta = 0L, generate_fb_snp_offsets = FALSE, run_fb_subset = FALSE, run_fb_grid_offset = 0L, return_extra = FALSE, return_gamma = FALSE, return_hapDosage = TRUE, update_in_place = FALSE, pass_in_alphaBeta = FALSE, output_haplotype_dosages = FALSE, snp_start_1_based = -1L, snp_end_1_based = -1L, grid = 0L, rescale = FALSE) {
    .Call('_STITCH_forwardBackwardHaploid', PACKAGE = 'STITCH', sampleReads, eHapsCurrent_tc, alphaMatCurrent_tc, transMatRate_tc_H, priorCurrent_m, alphaHat_t, betaHat_t, gamma_t, eMatGrid_t, maxDifferenceBetweenReads, maxEmissionMatrixDifference, Jmax, suppressOutput, model, gammaSum0_tc, gammaSum1_tc, alphaMatSum_tc, hapSum_tc, priorSum_m, pRgivenH1, pRgivenH2, run_pseudo_haploid, blocks_for_output, prev_list_of_alphaBetaBlocks, i_snp_block_for_alpha_beta, generate_fb_snp_offsets, run_fb_subset, run_fb_grid_offset, return_extra, return_gamma, return_hapDosage, update_in_place, pass_in_alphaBeta, output_haplotype_dosages, snp_start_1_based, snp_end_1_based, grid, rescale)
}

#' @export
rcpp_sample_path <- function(read_labels, eMatRead_t, sampleReads, maxDifferenceBetweenReads, Jmax, priorCurrent_m, transMatRate_tc_H, alphaMatCurrent_tc, s) {
    .Call('_STITCH_rcpp_sample_path', PACKAGE = 'STITCH', read_labels, eMatRead_t, sampleReads, maxDifferenceBetweenReads, Jmax, priorCurrent_m, transMatRate_tc_H, alphaMatCurrent_tc, s)
}

#' @export
rcpp_make_smoothed_rate <- function(sigmaSum_unnormalized, sigma_rate, L_grid, grid_distances, nGrids, shuffle_bin_radius, verbose = FALSE) {
    .Call('_STITCH_rcpp_make_smoothed_rate', PACKAGE = 'STITCH', sigmaSum_unnormalized, sigma_rate, L_grid, grid_distances, nGrids, shuffle_bin_radius, verbose)
}

#' @export
rcpp_calculate_hwe_p <- function(reference_hap) {
    .Call('_STITCH_rcpp_calculate_hwe_p', PACKAGE = 'STITCH', reference_hap)
}

#' @export
test_eHaps_options <- function(cube_eHaps_t, list_of_eHaps_t, gamma_t, eHaps_input, option, nSNPs, K, S) {
    .Call('_STITCH_test_eHaps_options', PACKAGE = 'STITCH', cube_eHaps_t, list_of_eHaps_t, gamma_t, eHaps_input, option, nSNPs, K, S)
}

#' @export
rcpp_make_column_of_vcf <- function(gp_t, use_read_proportions, use_state_probabilities, read_proportions, q_t) {
    .Call('_STITCH_rcpp_make_column_of_vcf', PACKAGE = 'STITCH', gp_t, use_read_proportions, use_state_probabilities, read_proportions, q_t)
}

