# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_header_using_SeqLib <- function(file_name) {
    .Call('STITCH_get_header_using_SeqLib', PACKAGE = 'STITCH', file_name)
}

#' @export
get_sample_data_from_SeqLib <- function(region, file_name, reference = "") {
    .Call('STITCH_get_sample_data_from_SeqLib', PACKAGE = 'STITCH', region, file_name, reference)
}

#' @export
increment2N <- function(yT, xT, y, z) {
    .Call('STITCH_increment2N', PACKAGE = 'STITCH', yT, xT, y, z)
}

#' @export
cpp_cigar_split <- function(strings) {
    .Call('STITCH_cpp_cigar_split', PACKAGE = 'STITCH', strings)
}

#' @export
pseudoHaploid_update_model_9 <- function(pRgivenH1, pRgivenH2, eMatHap_t1, eMatHap_t2, gamma_t1, gamma_t2, K, srp) {
    .Call('STITCH_pseudoHaploid_update_model_9', PACKAGE = 'STITCH', pRgivenH1, pRgivenH2, eMatHap_t1, eMatHap_t2, gamma_t1, gamma_t2, K, srp)
}

#' @export
reformatReads <- function(mapq, readStart, readEnd, numberOfReads, T, L, seqRead, qualRead, ref, alt, splitCigarRead, lengthOfSplitCigarRead, bqFilter, verbose) {
    .Call('STITCH_reformatReads', PACKAGE = 'STITCH', mapq, readStart, readEnd, numberOfReads, T, L, seqRead, qualRead, ref, alt, splitCigarRead, lengthOfSplitCigarRead, bqFilter, verbose)
}

#' @export
forwardBackwardDiploid <- function(sampleReads, nReads, pi, transMatRate_t, alphaMat_t, eHaps_t, maxDifferenceBetweenReads, whatToReturn, Jmax, suppressOutput) {
    .Call('STITCH_forwardBackwardDiploid', PACKAGE = 'STITCH', sampleReads, nReads, pi, transMatRate_t, alphaMat_t, eHaps_t, maxDifferenceBetweenReads, whatToReturn, Jmax, suppressOutput)
}

#' @export
forwardBackwardHaploid <- function(sampleReads, nReads, pi, transMatRate_t, alphaMat_t, eHaps_t, maxDifferenceBetweenReads, whatToReturn, Jmax, suppressOutput, model, pRgivenH1, pRgivenH2, pState) {
    .Call('STITCH_forwardBackwardHaploid', PACKAGE = 'STITCH', sampleReads, nReads, pi, transMatRate_t, alphaMat_t, eHaps_t, maxDifferenceBetweenReads, whatToReturn, Jmax, suppressOutput, model, pRgivenH1, pRgivenH2, pState)
}

#' @export
cpp_read_reassign <- function(ord, qnameInteger_ord, sampleReadsRaw, verbose) {
    .Call('STITCH_cpp_read_reassign', PACKAGE = 'STITCH', ord, qnameInteger_ord, sampleReadsRaw, verbose)
}

